# Generated by Django 5.1.4 on 2024-12-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_project_app', '0002_typeproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='TypeProducts/backgrounds/'),
        ),
    ]
