# Generated by Django 5.1.4 on 2024-12-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_project_app', '0003_typeproduct_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeproduct',
            name='background',
            field=models.ImageField(upload_to='TypeProducts/backgrounds/'),
        ),
    ]
